# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
